main/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'main.views.home', name = 'home'),
    #url(r'^new-entry/$', 'main.views.new_entry', name = 'new_entry'),
    url(r'^update-uids/(?P<proj_pk>\d+)/$', 'main.views.update_uids',
        name = 'update-uids'),
    url(r'^update-uids/(?P<proj_pk>\d+)/completed-old/(?P<role_id>\d+)/$', 'main.views.add_completed_entry',
        name = 'add-completed-entry'),
    url(r'^update-uids/(?P<proj_pk>\d+)/completed/$', 'main.views.update_completed',
        name = 'update-completed'),
    url(r'^add-completed-entry-done/(?P<role_id>\d+)/$', 'main.views.add_completed_entry_done',
        name = 'add-completed-entry-done'),
    url(r'^update-uids/(?P<proj_pk>\d+)/not-completed/(?P<role_id>\d+)/$', 'main.views.add_uncompleted_entry',
        name = 'add-uncompleted-entry'),
    url(r'^add-uncompleted-entry-done/(?P<role_id>\d+)/$', 'main.views.add_uncompleted_entry_done',
        name = 'add-uncompleted-entry-done'),
    url(r'^manage-uids/(?P<role_id>\d+)/$', 'main.views.manage_uids',
        name = 'manage-uids'),
    url(r'^manage-uids/(?P<role_id>\d+)/subordinate/(?P<sub_role>\d+)/$',
        'main.views.manage_sub_uids', name = 'manage-sub-uids'),
    url(r'^manage-uids/(?P<role_id>\d+)/auto-distribute/$',
        'main.views.auto_distribute_uids', name = 'auto-distribute-uids'),
    url(r'^import-uids/(?P<role_id>\d+)/$', 'main.views.import_uids',
        name = 'import-uids'),
    url(r'^get-error-types/(?P<role_id>\d+)/$', 'main.views.get_error_types',
        name = 'get_error_types'),
    url(r'^get-uid-list/(?P<role_id>\d+)/$', 'main.views.get_uid_list',
        name = 'get_uid_list'),
    url(r'^get-questions/(?P<role_id>\d+)/$', 'main.views.get_questions',
        name = 'get_questions'),
    url(r'^get-choices/(?P<role_id>\d+)/$', 'main.views.get_choices',
        name = 'get_choices'),

)

urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('main.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^admin/', include(admin.site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.db.models import Q
from django.db.models.query import QuerySet
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User

from mptt.models import MPTTModel
from mptt.fields import TreeForeignKey
from tags.models import Tag

class QuerySetManager(models.Manager):

    def get_query_set(self):
        return self.model.QuerySet(self.model)
    def __getattr__(self, name):
        return getattr(self.get_query_set(), name)

    use_for_related_fields = True

class ErrorType(MPTTModel):
    '''
    Possible errors which can occur in the survey. These are nested. An
    error could have multiple suberrors to be choosen from.
    '''
    name = models.CharField(_('name'), max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True,
                             related_name='suberrors')

    class MPTTMeta:
        order_insertion_by = ['name']
        parent_attr = 'parent'

    def __unicode__(self):
        return '%s' %(self.name.title())

class Role(MPTTModel):
    '''
    This will generate a hierarchy of people according to their
    posts.
    '''
    name = models.CharField(_('name'), max_length=100)
    head = TreeForeignKey('self', null=True, blank=True,
                          related_name='subordinate')
    user = models.ForeignKey(User)

    class MPTTMeta:
        order_insertion_by = ['name']
        parent_attr = 'head'

    def __unicode__(self):
        return self.name.title()

    def get_questionnaire(self):
        return self.get_root().questionnaire
    get_questionnaire.short_description = _('questionnaire')

    def managed_uids(self):
        query = Q(role__in=self.get_children()) | Q(role=self)
        return self.get_questionnaire().uidstatus_set.filter(query)

    def uids(self):
        '''
        This fetches the list of uids which are under a role's
        responsiblity.
        A role has uids assigned to it or if none is, it will be
        responsible for all uids for which its head is and this
        traverses up the hierarchy tree.

        A Role will have uids from the closest ancestor (or itself) who
        has a set.

        Eg:
        Let this be the tree:
        Questionnaire: 300
        A
          B (200)
            D
              G
              H
            E
              I
          C
            F
              J
              K

        Now if only B has some uids asigned, then D, E will have same uid
        sets as B and so would G, H, I.
        The rest will be open for distribution and under everybody's
        (except B subtree's) responsibility.
        '''
        questionnaire = self.get_questionnaire()
        questionnaire_uids = questionnaire.uidstatus_set.all()

        ancestors = self.get_ancestors(include_self=True)
        # Get all uids which are either assigned to any of ancestors
        # or to no one
        query =  Q(role__in=ancestors) | Q(role__isnull=True)
        return questionnaire_uids.filter(query)

    def uids_count(self):
        return self.uids().count()

class Questionnaire(models.Model):
    name = models.CharField(_('name'), max_length=100)
    users = models.ManyToManyField(User, blank=True)
    # This stores the topmost node of the tree whole children form the
    # hierarchy
    hierarchy = models.OneToOneField(Role, blank=True, null=True,
                                     related_name='questionnaire')
    # Tree heads of errors which can occur in the questionnaire
    error_types = models.ManyToManyField(ErrorType, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)

    def __unicode__(self):
        return self.name.title()

    def get_descendants(self):
        return self.hierarchy.get_descendants(include_self=True)

    def get_leafnodes(self, inc_self=True):
        return self.hierarchy.get_leafnodes(include_self=inc_self)

    def get_questions(self):
        return Question.objects.all().filter(questionnaire=self)

    def total_uids(self):
        return self.uidstatus_set.count()

    def done_uids(self):
        return self.uidstatus_set.filter(completer__isnull=False).count()

    def completion(self):
        return 100 * self.done_uids()/self.total_uids() if self.total_uids() else 0

class Question(models.Model):
    '''
    Extra multiple choice question to be asked if survey was completed.
    For example -
    Question - What was child's age?
    Choices -
    1. 3
    2. 4
    3. 5
    '''
    name = models.CharField(_('name'), max_length=100)
    field_name = models.CharField(_('field_name'), max_length=40)
    questionnaire = models.ForeignKey(Questionnaire)

    def __unicode__(self):
        return '%s' %(self.name)

    def get_choices(self):
        return self.choice_set.all()

class Choice(models.Model):
    name = models.CharField(_('name'), max_length=100)
    question = models.ForeignKey(Question)

    def __unicode__(self):
        return '%s' %(self.name.title())

class UIDStatus(models.Model):
    '''
    This will be table storing the uids from excel exported sheets, linked
    to the db pks.
    '''
    uid = models.CharField(_('unique identifier'), max_length=30,
            unique=True)
    extra_details = models.TextField(_('extra details'), blank=True)
    #The people who are responsible for this survey uid.
    errors = models.ManyToManyField(ErrorType, null=True, blank=True,
                                    through='UIDError')
    questions = models.ManyToManyField(Question, null=True, blank=False,
            through='UIDQuestion')
    questionnaire = models.ForeignKey(Questionnaire)
    role = TreeForeignKey(Role, blank=True, null=True,
                             verbose_name=_('main responsible person'),
                             related_name='uidstatuses')

    # This field name is not a word will be updated as soon as this Q is
    # answered: http://j.mp/j4VDIO
    completer = models.ForeignKey(Role, blank=True, null=True,
            verbose_name=_('who did it?'))
    date = models.DateField(_('date of completion'), blank=True, null=True)

    objects = QuerySetManager()

    class Meta:
        verbose_name =  _('UID')

    class QuerySet(QuerySet):
        def pending(self):
            return self.filter(completer__isnull=True)

    def __unicode__(self):
        role = self.role.user if self.role else 'Unassigned'
        return '%s - %s' %(self.uid, role)

    def user(self):
        return self.role.user

    def done(self):
        return True if self.completer else False
    done.boolean = True

    def responsible_people(self):
        '''
        Gives the leaf nodes of the tree below a uid-role's nodes or all
        questionnaire leaf nodes if none is assigned.
        '''
        if self.role:
            return self.role.get_leafnodes(include_self=True)
        else:
            return self.questionnaire.get_leafnodes()


class UIDError(models.Model):
    '''
    An error for a uid - error M2M will be created through this.
    It is where detail is to be defined
    '''
    etype = models.ForeignKey(ErrorType)
    uid_status = models.ForeignKey(UIDStatus)
    details = models.TextField(_('error details'), blank=True,
                               help_text="enter extra details just in case\
                               useful.") #Revise this

class UIDQuestion(models.Model):
    '''
    A question for a completed will be created through this.
    '''
    question = models.ForeignKey(Question)
    uid_status = models.ForeignKey(UIDStatus)
    selected_choice = models.ForeignKey(Choice)

#For quick creation of fixtures.

def get_dummy_user(username):
    user, new = User.objects.get_or_create(username=username)
    if new:
        user.set_password(username)
        user.save()
    return user

def create_role(name, head=None, username=None):
    if username:
        user = get_dummy_user(username)
    else:
        user = get_dummy_user(name)

    return Role.objects.get_or_create(name=name, user=user, head=head)[0]

def create_base_role_tree():
    superhead = create_role('A', username='test')

    r1 = create_role('B', superhead)
    r11 = create_role('D', r1)
    r111 = create_role('H', r11)

    r12 = create_role('E', r1)
    r13 = create_role('F', r1)
    r131 = create_role('I', r13)

    r2 = create_role('C', superhead)
    r21 = create_role('G', r2)
    r211 = create_role('J', r21)
    r212 = create_role('K', r21)

    questionnaire, new = Questionnaire.objects.get_or_create(pk=1)
    if new:
        questionnaire.name = 'TestQS'
        questionnaire.save()
    questionnaire.hierarchy = superhead
    questionnaire.save()

    print superhead
    print r1, r11, r111
    print r12, r13, r131
    print r2, r21, r211, r212
    print questionnaire

main/templates/main/add_completed_entry.html
{% extends 'base.html' %}
{% block head %}
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"
    type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/validate_date.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
            var role_id = {{ role.id }};
            var questions;
            var choices;
            var uid_list = new Array();
            var extra_details = new Array();
            form_html = '<hr/><form action="" method="post" class="entry_form">';
            form_html += $('.entry_form:first').clone().html();
            form_html += '</form>';

            for(i=0;i<20;i++){
            $(form_html).insertAfter($('.entry_form:last'));
            }

            $('#date').live('change', function(){
                var d=$(this).val();
                $('.hidden_date').each(function(){
                    $(this).val(d);
                    });
                });

            $.getJSON('/get-choices/'+role_id, function(data){
                    choices = data;
                    $.getJSON('/get-questions/'+role_id, function(data){
                        questions = data;
                        $('.entry_form').each(function(){
                            var output = '<input type="hidden" name="date" class="hidden_date" value="'+$('#date').val()+'"></input>';
            $(output).insertBefore($(this).find('.uid'));

                            index=0;
                            $(this).find('.question').each(function(){
                                output = '<tr><th>' + questions[index].fields.name + '</th></tr>';
                                $(output).insertAfter($(this));
                                output = '<option value="" selected="selected">---------</option>';
                                for(i=0;i<choices.length;i++){
                                if(choices[i].fields.question==questions[index].pk)
                                output += '<option value="'+choices[i].pk+'">'+choices[i].fields.name+'</option>';
                                }
                                $(this).parent().find('.choice').html(output);
                                $(this).val(questions[index].pk);
                                index += 1;
                                });
                            });
                        });
                    });

            $.getJSON('/get-uid-list/'+role_id, function(data){
                    for(i=0;i<data.length;i++){
                    uid_list.push(String(data[i].fields.uid));
                    extra_details.push(data[i].fields.extra_details);
                    }
                    $(".uid").each(function(){
                        $(this).autocomplete({source: uid_list});
                        $(this).bind('autocompleteselect', function(event,ui){
                            $(this).parent().find('.extra_details').remove();
                            index = uid_list.indexOf(String($(this).val()));
                            if (index != -1){
                            $('<span class="extra_details" display="block" style="font-size:9px;line-height:50%;"><br/>'+ extra_details[index] + '</span>').insertAfter($(this));
                            }
                            });
                        $(this).live('change', function(){
                            $(this).parent().find('.extra_details').remove();
                            index = uid_list.indexOf(String($(this).val()));
                            if (index != -1){
                            $('<span class="extra_details" display="block" style="font-size:9px; line-height:50%;"><br/>'+ extra_details[index] + '</span>').insertAfter($(this));
                            }
                            });
                        });
            });


            $('#date').datepicker({dateFormat:'yy-mm-dd', inline:true});
            $('#date').live('change', function(){
                    if(isDate($(this).val())==false){
                    $(this).focus();
                    return false;
                    }
                    return true;
                    });
            $(".entry_form").each(function(){
                    $(this).submit(function(e){
                        e.preventDefault();
                        //validating date
                        if(isDate($('#date').val())==false){
                        return false;
                        }

                        //validating uid
                        if($(this).find('.uid').val() == ''){
                        alert("UID can't be left empty");
                        return false;
                        }
                        else{
                        if ($.inArray($(this).find('.uid').val(), uid_list)==-1){
                        alert("You have entered invalid UID.\nPlease retype and select one from suggestions.");
                        return false;
                        }
                        }

                        //checking if choices were selected.
                        var errors_count = 0;
                        $(this).find('.choice').each(function(){
                                if($(this).val()==''){
                                alert("All questions need to be answered.");
                                errors_count += 1;
                                return false;
                                }
                                });
                        if(errors_count>0)
                            return false;

                        //It means form was valid
                        var form=this;
                        $.ajax({
type: "POST",
url:$(this).attr('action'),
data:$(this).serialize(),
success:function(response){
if(String(response)=='Success'){
$(form).find('#errors').remove();
$(form).hide();
$('<b style="color:green; display:block;">Form has been submitted successfully.</b>').insertAfter($(form));
var uid = $(form).find('.uid').val();
uid_list = $.grep(uid_list, function(val) {return val != uid; });
if(uid_list.length==0){
$('.entry_form').each(function(){
    $(this).hide();
    });
$('<h3 style="color:blue;">No more UIDs left for this surveyor.</h3>').insertAfter($('#date'));
return true;
}
$('.uid').each(function(){
    $(this).autocomplete({source: uid_list});
    });
return true;
} else {
    $(form).find('#errors').remove();
    $('<b style="color:red; display:block;" id="errors">Some errors in form.</b>').insertAfter($(form).find('.submit').parent());
    return false;
}
}
});
});
});

});
</script>
<link rel='stylesheet' href="{{ STATIC_URL }}css/jquery-ui-1.8.13.custom.css" type = "text/css"/>
{% endblock %}
{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url update-uids role.get_questionnaire.id %}">Update UIDs status</a> >
<a class="button" href="{% url add-completed-entry role.get_questionnaire.id role.id %}">{{ role }}</a>

<h3>Add Completed Surveys</h3>
<table>
    <tr>
        <th>Surveyor:</th>
        <td>{{ role.name }}</td>
    </tr>
    <tr>
        <th>Date of completion:</th>
        <td><input type="text" name="date" value="{{ date|date:"Y-m-j" }}" id="date"></td>
    </tr>
</table>
<form action="" method="post" class="entry_form">
    {{ formset.management_form }}
    <table>
        {{ formset.non_form_errors.as_ul }}
        {% for field in uid_form %}
        <th>{{ field.label }} : </th>
        <td>
            {% if forloop.first %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% endif %}
            {{ field }}
        </td>
        {% endfor %}
        {% for form in formset %}
        <td>
            <table>
                {% for field in form.visible_fields %}
                <tr><td>
                        {# Include the hidden fields in the form #}
                        {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% endif %}
                        {{ field.errors.as_ul }}
                        {{ field }}
                </td></tr>
                {% endfor %}
            </table>
        </td>
        {% endfor %}
        <td><input type="submit" value="Submit" class=".submit"/></td>
        {% csrf_token %}
    </table>
</form>
<!--<a href="javascript:void(0)" class="add-row">
    <img src="{{ STATIC_URL }}admin/img/admin/icon_addlink.gif" title="Add another form"/>
</a>
-->
{% endblock %}

main/templates/main/add_completed_entry_done.html
{% extends 'base.html' %}
{% block content %}
<h3>Add Completed Surveys Done</h3>
All details have been saved successfully.<br/><br/>
<a href="{% url select-surveyor role.get_questionnaire.id %}">Click here</a> to add
more entries.<br/><br/>
<a href="/">Click here</a> to goto home page.
{% endblock %}

main/templates/main/add_uncompleted_entry_done.html
{% extends 'base.html' %}
{% block content %}
<h3>Add Uncompleted Surveys Done</h3>
All details have been saved successfully.<br/><br/>
<a href="{% url select-surveyor role.get_questionnaire.id %}">Click here</a> to add
more entries.<br/><br/>
<a href="/">Click here</a> to goto home page.
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}

{% block content %}
<h2>Your Current Surveys</h2>
{% for role in user.role_set.all %}
{% if role.get_questionnaire %}
<h3>{{ role.get_questionnaire }}</h3>

<table class="styled">
    <tr>
        <td>{{ role.get_questionnaire.total_uids }} UID{{ role.get_questionnaire.total_uids|pluralize }} total</td>
        <td>{{ role.get_questionnaire.completion }} % done</td>
    </tr>
</table>
<p>
    <h5>Your Tasks:</h5>
    <a class="button" href="{% url update-uids role.get_questionnaire.id %}">Update UIDs status</a>
    <a class="button" href="{% url manage-uids role.id %}">Manage UIDs</a>
    {% if role.is_root_node or request.user.is_superuser %}
    <a class="button" href="{% url import-uids role.id %}">Import UIDs</a>
    {% endif %}
    <a class="button" href="">View Detailed Status</a>
</p>
<hr/>
{% endif %}
{% endfor %}
{% endblock %}

main/templates/main/import_complete.html
{% extends 'base.html' %}
{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url import-uids role.id %}">Import UIDs</a>

<h3>Import UIDs</h3>
<p>
    {{ result }}
</p>
{% endblock %}

main/templates/main/import_uids.html
{% extends 'base.html' %}
{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url import-uids role.id %}">Import UIDs</a>

<h3>Import UIDs</h3>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr><td><input type="submit" value="Submit"></td></tr>
    </table>
</form>
{% endblock %}

main/templates/main/manage_sub_uids.html
{% extends 'base.html' %}

{% block head %}
{{ form.media }}

{% endblock %}
{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url manage-uids role.id %}">Manage UIDs</a> >
<a class="button" href="{% url manage-sub-uids role.id sub.id %}">{{ sub }}</a>
<h3>Subordinate: {{ sub }}</h3>
{% if manages %}
<form action='' method='post'>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value='Update'/>
</form>
{% else %}
You have not been assigned UIDs for managing.
{% endif %}
{% endblock %}

main/templates/main/manage_uids.html
{% extends 'base.html' %}

{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url manage-uids role.id %}">Manage UIDs</a>

<p>
    You have responsibility for managing {{ role.managed_uids.count }} pending
    UID{{ role.managed_uids.count|pluralize }} of which
    {{ role.uidstatuses.pending.count }}
    {{ role.uidstatuses.pending.count|pluralize:"is,are" }} yet to be divided in
    your subordinates.
</p>
<h3>Distribute UID management to subordinates:</h3>
<table class="styled">
    <tr>
        <th>Subordinate</th>
        <th>UIDs assigned</th>
    </tr>
    {% for sub in role.get_children %}
    <tr>
        <td>{{ sub }}</td>
        <td>{{ sub.uidstatuses.count }}</td>
        <td><a class="button" href="{% url manage-sub-uids role.id sub.id %}">Manage</a></td>
    </tr>
    {% endfor %}
</table>
{% if role.uidstatuses.all %}
<p>
    <a href='{% url auto-distribute-uids role.id %}' class="button" title="Equally assign UIDs to subordinates">Automatically distribute</a>
</p>
{% endif %}

{% endblock %}

main/templates/main/select_surveyor.html
{% extends 'base.html' %}

{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url select-surveyor role.get_questionnaire.id %}">Update UIDs status</a>

<p>
    You and your subordinates have responsibility of {{ pending_uids }} UID{{ pending_uids|pluralize }} yet to be updated
</p>
<h3>Update subordinates UIDs status:</h3>
<table class="styled">
    <tr>
        <th>Surveyor</th>
        <th>Completed</th>
        <th>Not Completed</th>
    </tr>
    {% for surveyor in surveyors %}
    <tr>
        <td>{{ surveyor.name }}</td>
        <td><a class="button" href="{% url add-completed-entry surveyor.id %}">Add</a></td>
        <td><a class="button" href="{% url add-uncompleted-entry surveyor.id %}">Add</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

main/templates/main/update_completed.html
{% extends 'base.html' %}
{% load adminmedia %}
{% block head %}
<script type="text/javascript">
    head.js('/static/js/jquery.formset.min.js');

// Updates the dates in formset forms
function updateDates(){
    return;
    date_input_val = $("#formsetDate").val();
    date_fields = $('[id$="-date"]');
    date_fields.datepicker({dateFormat:'yy-mm-dd', inline:true});
    date_empty_fields = $('[id$="-date"]');

    // For each form date field add the global date value if none is
    // already present
    date_fields.each(function(index){
        if (!this.value){
            this.value = date_input_val;
        };
    });
};

head.ready(function(){
    $.datepicker.setDefaults({dateFormat:'yy-mm-dd'});

    //$(function() {
    //    $('#formsetForm tbody tr').formset({'added':updateDates});
    //});

    $(function() {

        // Create the global datepicker
        $('[id$="-date"]').datepicker({
            onSelect: updateDates
        });
        // Set global datepicker value to now
        //$('#formsetDate').datepicker("setDate", now);

        // Update all empty dates to pick value from global datepicker
        //updateDates();
    });
});
</script>
{% endblock %}

{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url update-uids role.get_questionnaire.id %}">Update UIDs status</a> >
<a class="button" href="{% url update-completed role.get_questionnaire.id %}">Update completed UIDs</a>
<!--
   -<p>
   -    Date: <input type="text" name="completion_date" id="formsetDate"/>
   -</p>
   -->
<form id="formsetForm" method="post" action="">
    <table widht="100%">
        <tbody>
            <tr>
                {% for field in formset.empty_form.visible_fields %}
                <td>{{ field.label }}</td>
                {% endfor %}
            </tr>
            {% for form in formset.forms %}
            <tr>
                {% for field in form.hidden_fields %}
                <td class="hidden">{{ field }}</td>
                {% endfor %}
                {% for field in form.visible_fields %}
                <td>{% if field.errors %}{{ field.errors }}{% endif %}{{ field }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ formset.management_form }}
    <br/>
    {% csrf_token %}
    <input type="submit" value="Post"/>
</form>
{% endblock %}

main/templates/main/update_uids.html
{% extends 'base.html' %}

{% block content %}
<a class="button" href="/">Home</a> >
<a class="button" href="{% url update-uids role.get_questionnaire.id %}">Update UIDs status</a>

<h3>Update subordinates UIDs status:</h3>

<p>
<a class="button" href="{% url update-completed role.get_questionnaire.id %}">Add Completed (General)</a>
</p>

<table class="styled">
    <tr>
        <th>Surveyor</th>
        <th>Completed</th>
        <th>Not Completed</th>
        <th>Pending UIDs</th>
    </tr>
    {% for surveyor in surveyors %}
    <tr>
        <td>{{ surveyor.name }}</td>
        <td><a class="button" href="{% url add-completed-entry role.get_questionnaire.id surveyor.id %}">Add</a></td>
        <td><a class="button" href="{% url add-uncompleted-entry role.get_questionnaire.id surveyor.id %}">Add</a></td>
        <td>{{ surveyor.uids.pending.count }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}